// Code generated by "stringer -type SecNum"; DO NOT EDIT

package main

import "fmt"

const _SecNum_name = "SecTypeInfoSecImpSecImpFileSecRefSecGIDMapSecGIDSecNameMapSecNameSecBstrSecTypeDescSecArrayDescSecCustomSecCustomGIDSecTrash1SecTrash2"

var _SecNum_index = [...]uint8{0, 11, 17, 27, 33, 42, 48, 58, 65, 72, 83, 95, 104, 116, 125, 134}

func (i SecNum) String() string {
	if i < 0 || i >= SecNum(len(_SecNum_index)-1) {
		return fmt.Sprintf("SecNum(%d)", i)
	}
	return _SecNum_name[_SecNum_index[i]:_SecNum_index[i+1]]
}
