// Code generated by "stringer -type VarKind"; DO NOT EDIT

package main

import "fmt"

const (
	_VarKind_name_0 = "VarEmptyVarNullVarInt16VarInt32VarFloat32VarFloat64VarCurrencyVarDateVarBstrVarDispatchVarErrorVarBoolVarVariantVarUnknownVarDecimal"
	_VarKind_name_1 = "VarInt8VarUint8VarUint16VarUint32VarInt64VarUint64VarIntVarUintVarVoidVarHresultVarVoidstarVarSafearrayVarCarrayVarUserdefinedVarLpstrVarLpwstrVarRecordVarIntptrVarUintptr"
)

var (
	_VarKind_index_0 = [...]uint8{0, 8, 15, 23, 31, 41, 51, 62, 69, 76, 87, 95, 102, 112, 122, 132}
	_VarKind_index_1 = [...]uint8{0, 7, 15, 24, 33, 41, 50, 56, 63, 70, 80, 91, 103, 112, 126, 134, 143, 152, 161, 171}
)

func (i VarKind) String() string {
	switch {
	case 0 <= i && i <= 14:
		return _VarKind_name_0[_VarKind_index_0[i]:_VarKind_index_0[i+1]]
	case 16 <= i && i <= 34:
		i -= 16
		return _VarKind_name_1[_VarKind_index_1[i]:_VarKind_index_1[i+1]]
	default:
		return fmt.Sprintf("VarKind(%d)", i)
	}
}
